# Generated by Django 5.0.7 on 2024-09-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opencalapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="numCals",
        ),
    ]
