# Generated by Django 5.0.7 on 2024-08-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencalapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="isFriend",
            field=models.BooleanField(default=True),
        ),
    ]
