# Generated by Django 5.0.7 on 2024-08-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencalapp", "0002_customuser_isfriend"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daysBusy", models.IntegerField(default=26)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="calendars",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="opencalapp.calendar"
            ),
        ),
    ]
