# Generated by Django 5.0.7 on 2024-08-12 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencalapp", "0003_calendar_customuser_calendars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendar",
            name="daysBusy",
        ),
        migrations.AddField(
            model_name="calendar",
            name="name",
            field=models.CharField(default="Calendar Name", max_length=20),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="opencalapp.calendar",
                    ),
                ),
            ],
        ),
    ]
