# Generated by Django 5.0.7 on 2024-08-12 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencalapp", "0004_remove_calendar_daysbusy_calendar_name_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_calendars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
