# Generated by Django 5.0.7 on 2024-08-13 03:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencalapp", "0005_calendar_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="contributors",
            field=models.ManyToManyField(
                related_name="active_calendars", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="last_modified",
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 0, 0)),
        ),
    ]
