# Generated by Django 5.0.7 on 2024-08-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opencalapp", "0006_calendar_contributors_calendar_last_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="isFriend",
        ),
    ]
