# Generated by Django 5.0.7 on 2024-08-15 02:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencalapp", "0007_remove_customuser_isfriend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="contributors",
            field=models.ManyToManyField(
                blank=True, related_name="active_calendars", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="last_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
