# Generated by Django 5.0.7 on 2024-08-15 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencalapp", "0008_alter_calendar_contributors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friend_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                default=models.ForeignKey(
                    default=1,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="owned_calendars",
                    to=settings.AUTH_USER_MODEL,
                ),
                related_name="active_calendars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
